version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mail@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
     - ./docker/pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  local_pgdata:
  pgadmin-data: